"""add custom_role_id to employees

Revision ID: cd8d3ec0f9cb
Revises: 037_add_custom_roles
Create Date: 2026-08-25 09:33:39.489453
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'cd8d3ec0f9cb'
down_revision: Union[str, None] = '037_add_custom_roles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'mcp_token',
               existing_type=sa.VARCHAR(length=500),
               comment='DEPRECATED — legacy plaintext token, no longer read or written',
               existing_comment='Bearer token for MCP authentication',
               existing_nullable=True)
    op.alter_column('employees', 'mcp_token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='HMAC-SHA256(pepper, token) — primary lookup key for MCP auth',
               existing_nullable=True)
    op.alter_column('employees', 'mcp_token_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment='First 12 chars of the token for UI display (e.g. ark_aBcD…)',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'employee_id',
               existing_type=sa.UUID(),
               comment='Caller; NULL if token resolution failed before call',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'tool_name',
               existing_type=sa.VARCHAR(length=80),
               comment='MCP tool invoked: search_wiki, read_wiki_page, propose_wiki_edit, ...',
               existing_nullable=False)
    op.alter_column('mcp_query_log', 'query_text',
               existing_type=sa.TEXT(),
               comment='Search/query string when applicable',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'scope_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Department/project/filters used for the call',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'result_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='IDs returned (wiki_page_id or source_id list)',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='ok | error | denied',
               existing_nullable=False,
               existing_server_default=sa.text("'ok'::character varying"))
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.UUID(),
               comment='Employee who caused the event (author/reviewer)',
               existing_nullable=True)
    op.drop_constraint(op.f('oauth_auth_codes_code_key'), 'oauth_auth_codes', type_='unique')
    op.drop_index(op.f('ix_oauth_auth_codes_code'), table_name='oauth_auth_codes')
    op.create_index(op.f('ix_oauth_auth_codes_code'), 'oauth_auth_codes', ['code'], unique=True)
    # op.drop_constraint(op.f('oauth_clients_client_id_key'), 'oauth_clients', type_='unique')
    # op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    # op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.drop_constraint('oauth_auth_codes_client_id_fkey', 'oauth_auth_codes', type_='foreignkey')
    op.drop_constraint(op.f('oauth_clients_client_id_key'), 'oauth_clients', type_='unique')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_foreign_key(
        'oauth_auth_codes_client_id_fkey',
        'oauth_auth_codes', 'oauth_clients',
        ['client_id'], ['client_id']
    )
    op.drop_index(op.f('ix_source_chunk_embeddings_1024_hnsw'), table_name='source_chunk_embeddings_1024', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_source_chunk_embeddings_1024_model'), table_name='source_chunk_embeddings_1024')
    op.drop_index(op.f('ix_source_chunk_embeddings_1024_source'), table_name='source_chunk_embeddings_1024')
    op.drop_index(op.f('ix_source_chunk_embeddings_1536_hnsw'), table_name='source_chunk_embeddings_1536', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_source_chunk_embeddings_1536_model'), table_name='source_chunk_embeddings_1536')
    op.drop_index(op.f('ix_source_chunk_embeddings_1536_source'), table_name='source_chunk_embeddings_1536')
    op.drop_index(op.f('ix_source_chunk_embeddings_3072_hnsw'), table_name='source_chunk_embeddings_3072', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_source_chunk_embeddings_3072_model'), table_name='source_chunk_embeddings_3072')
    op.drop_index(op.f('ix_source_chunk_embeddings_3072_source'), table_name='source_chunk_embeddings_3072')
    op.drop_index(op.f('ix_source_chunk_embeddings_768_hnsw'), table_name='source_chunk_embeddings_768', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_source_chunk_embeddings_768_model'), table_name='source_chunk_embeddings_768')
    op.drop_index(op.f('ix_source_chunk_embeddings_768_source'), table_name='source_chunk_embeddings_768')
    op.create_index(op.f('ix_source_chunk_extracts_source_id'), 'source_chunk_extracts', ['source_id'], unique=False)
    op.alter_column('sources', 'extracted_token_count',
               existing_type=sa.INTEGER(),
               comment='tiktoken cl100k_base count of full_text. Used by upload gate.',
               existing_nullable=True)
    op.alter_column('sources', 'auto_recover_count',
               existing_type=sa.INTEGER(),
               comment="Times sweep_stuck_processing_cron has flipped this source from 'processing' back to 'error'. Reset on successful plan_ready/ready. Gated by settings.max_auto_recover_attempts.",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sources', 'preserve_verbatim',
               existing_type=sa.BOOLEAN(),
               comment='If True, skip the LLM wiki pipeline (MRP). The raw full_text is chunked + embedded as-is into source_chunk_embeddings_<dim> so it is searchable in the same semantic pool as wiki pages, but never rewritten. For high-fidelity docs (decrees, official gazettes).',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('stats_daily_rollup', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC date the metric covers (midnight UTC)',
               existing_nullable=False)
    op.alter_column('stats_daily_rollup', 'metric_key',
               existing_type=sa.VARCHAR(length=80),
               comment='e.g. wiki.pages.total, mcp.queries.zero_result, draft.pending',
               existing_nullable=False)
    op.alter_column('stats_daily_rollup', 'dimensions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{department_id, project_id, tool_name, source}',
               existing_nullable=True)
    op.alter_column('stats_daily_rollup', 'dimensions_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='md5 of canonical-serialized dimensions; empty string when dimensions is NULL',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('ix_wiki_page_embeddings_1024_hnsw'), table_name='wiki_page_embeddings_1024', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_wiki_page_embeddings_1024_model'), table_name='wiki_page_embeddings_1024')
    op.drop_index(op.f('ix_wiki_page_embeddings_1536_hnsw'), table_name='wiki_page_embeddings_1536', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_wiki_page_embeddings_1536_model'), table_name='wiki_page_embeddings_1536')
    op.drop_index(op.f('ix_wiki_page_embeddings_3072_hnsw'), table_name='wiki_page_embeddings_3072', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_wiki_page_embeddings_3072_model'), table_name='wiki_page_embeddings_3072')
    op.drop_index(op.f('ix_wiki_page_embeddings_768_hnsw'), table_name='wiki_page_embeddings_768', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_wiki_page_embeddings_768_model'), table_name='wiki_page_embeddings_768')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wiki_page_embeddings_768_model'), 'wiki_page_embeddings_768', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_wiki_page_embeddings_768_hnsw'), 'wiki_page_embeddings_768', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_wiki_page_embeddings_3072_model'), 'wiki_page_embeddings_3072', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_wiki_page_embeddings_3072_hnsw'), 'wiki_page_embeddings_3072', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_wiki_page_embeddings_1536_model'), 'wiki_page_embeddings_1536', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_wiki_page_embeddings_1536_hnsw'), 'wiki_page_embeddings_1536', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_wiki_page_embeddings_1024_model'), 'wiki_page_embeddings_1024', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_wiki_page_embeddings_1024_hnsw'), 'wiki_page_embeddings_1024', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('stats_daily_rollup', 'dimensions_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='md5 of canonical-serialized dimensions; empty string when dimensions is NULL',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('stats_daily_rollup', 'dimensions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{department_id, project_id, tool_name, source}',
               existing_nullable=True)
    op.alter_column('stats_daily_rollup', 'metric_key',
               existing_type=sa.VARCHAR(length=80),
               comment=None,
               existing_comment='e.g. wiki.pages.total, mcp.queries.zero_result, draft.pending',
               existing_nullable=False)
    op.alter_column('stats_daily_rollup', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC date the metric covers (midnight UTC)',
               existing_nullable=False)
    op.alter_column('sources', 'preserve_verbatim',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If True, skip the LLM wiki pipeline (MRP). The raw full_text is chunked + embedded as-is into source_chunk_embeddings_<dim> so it is searchable in the same semantic pool as wiki pages, but never rewritten. For high-fidelity docs (decrees, official gazettes).',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sources', 'auto_recover_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Times sweep_stuck_processing_cron has flipped this source from 'processing' back to 'error'. Reset on successful plan_ready/ready. Gated by settings.max_auto_recover_attempts.",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sources', 'extracted_token_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='tiktoken cl100k_base count of full_text. Used by upload gate.',
               existing_nullable=True)
    op.drop_index(op.f('ix_source_chunk_extracts_source_id'), table_name='source_chunk_extracts')
    op.create_index(op.f('ix_source_chunk_embeddings_768_source'), 'source_chunk_embeddings_768', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_768_model'), 'source_chunk_embeddings_768', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_768_hnsw'), 'source_chunk_embeddings_768', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_source_chunk_embeddings_3072_source'), 'source_chunk_embeddings_3072', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_3072_model'), 'source_chunk_embeddings_3072', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_3072_hnsw'), 'source_chunk_embeddings_3072', ['embedding'], unique=False, postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_source_chunk_embeddings_1536_source'), 'source_chunk_embeddings_1536', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_1536_model'), 'source_chunk_embeddings_1536', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_1536_hnsw'), 'source_chunk_embeddings_1536', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_source_chunk_embeddings_1024_source'), 'source_chunk_embeddings_1024', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_1024_model'), 'source_chunk_embeddings_1024', ['model_spec_id'], unique=False)
    op.create_index(op.f('ix_source_chunk_embeddings_1024_hnsw'), 'source_chunk_embeddings_1024', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=False)
    op.create_unique_constraint(op.f('oauth_clients_client_id_key'), 'oauth_clients', ['client_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_oauth_auth_codes_code'), table_name='oauth_auth_codes')
    op.create_index(op.f('ix_oauth_auth_codes_code'), 'oauth_auth_codes', ['code'], unique=False)
    op.create_unique_constraint(op.f('oauth_auth_codes_code_key'), 'oauth_auth_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Employee who caused the event (author/reviewer)',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ok | error | denied',
               existing_nullable=False,
               existing_server_default=sa.text("'ok'::character varying"))
    op.alter_column('mcp_query_log', 'result_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='IDs returned (wiki_page_id or source_id list)',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'scope_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Department/project/filters used for the call',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'query_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Search/query string when applicable',
               existing_nullable=True)
    op.alter_column('mcp_query_log', 'tool_name',
               existing_type=sa.VARCHAR(length=80),
               comment=None,
               existing_comment='MCP tool invoked: search_wiki, read_wiki_page, propose_wiki_edit, ...',
               existing_nullable=False)
    op.alter_column('mcp_query_log', 'employee_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Caller; NULL if token resolution failed before call',
               existing_nullable=True)
    op.alter_column('employees', 'mcp_token_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='First 12 chars of the token for UI display (e.g. ark_aBcD…)',
               existing_nullable=True)
    op.alter_column('employees', 'mcp_token_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='HMAC-SHA256(pepper, token) — primary lookup key for MCP auth',
               existing_nullable=True)
    op.alter_column('employees', 'mcp_token',
               existing_type=sa.VARCHAR(length=500),
               comment='Bearer token for MCP authentication',
               existing_comment='DEPRECATED — legacy plaintext token, no longer read or written',
               existing_nullable=True)
    # ### end Alembic commands ###
